
service: mappin

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
package:
  include:
functions:
  updateUserClick: 
    handler: handler.updateUserClick
    events:
      - http:
          path: updateUserClick/
          method: PUT
  getUserClicks: 
    handler: handler.getUserClicks
    events:
      - http:
          path: getUserClicks/
          method: GET
resources:
  Resources:
    pathmapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
          BasePath: oauth2
          DomainName: ${file(./.serverless.env.yml):${opt:stage}.aws.DOMAIN_NAME}
          RestApiId: 
              Ref: ApiGatewayRestApi
          Stage: dev
    mappinTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: mappinTable
        AttributeDefinitions:
          - AttributeName: latLong
            AttributeType: S
        KeySchema:
          - AttributeName: latLong
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: mappinTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:Query
              Resource: arn:aws:dynamodb:*:*:table/mappinTable
        Roles:
          - Ref: IamRoleLambdaExecution