service: mappin

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
package:
  exclude:
    - node_modules/**
    - config/**
    - build/**
    - public/**
    - scripts/**
    - src/**
functions:
  updateUserClick: 
    handler: handler.updateUserClick
    events:
      - http:
          path: updateUserClick/
          method: post
          cors: true
  getUserClicks: 
    handler: handler.getUserClicks
    events:
      - http:
          path: getUserClicks/
          method: get
          cors: true
resources:
  Resources:
    mappinTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: mappinTable
        AttributeDefinitions:
          - AttributeName: latLong
            AttributeType: S
        KeySchema:
          - AttributeName: latLong
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: mappinTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:Query
              Resource: arn:aws:dynamodb:*:*:table/mappinTable
        Roles:
          - Ref: IamRoleLambdaExecution